version: 2

sources:
  - name: silver_nasa_data
    database: projeto-degelo
    schema: silver_nasa_data
    tables:
      - name: massa_gelo
        columns:
          - name: Data
            tests:
              - not_null
          - name: Entidade
            tests:
              - not_null
          - name: Variacao_Sazonal
            tests:
              - not_null
        
        